### ISSUE TITLE
Where can we find the nomino mapper python script?

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/mapper-nomino#4]
Hi Jeff/Michael,
Greetings..!

We are about to map our nomino data files. and we got this repository for nomino mappers but we couldn't find the mapper script here?

Can you help us providing the python script to map our nomino data?

Thanks.

**Comment by SaravananKalimuthu21** [comment]
Any update on this?

**Comment by jbutcher21** [comment]
Hi @SaravananKalimuthu21, we will be working on this this week.   You did get the already converted json we produced in the meantime, did you not?

**Comment by jbutcher21** [comment]
Ok , can you send us those so that we can see if the format is the same.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SaravananKalimuthu21** [comment]
Jeff, File links are sent to you via email.

Email Subject: NOMINO files to be uploaded further

**Comment by jbutcher21** [comment]
Hi Saravanan, 

Since the Nomino files are flat csv, we used the csv_mapper to map turn them into json.  The map files in this project include the human trafficking and the mob files.   I would like for you to take a stab at mapping the additional files yourself and even posting your additional mapping files to this GitHub project.  Please read the csv_mapper project and try it.   I would love your feedback on what worked and what didn't!

**Comment by SaravananKalimuthu21** [comment]
Hi Jeff,

We tried the csv mapper to map our flat csv files which i gave you in the email.

It gives us an inappropriate JSON output as mentioned below.

Mapper-CSV output:
![csv_mapper_output](https://user-images.githubusercontent.com/48215082/87141138-3e1fc400-c2c0-11ea-84cc-732d7d276782.png)

And the previous NOMINO mapped JSON files you sent is the same as we have now as a CSV. 

JSON file sent by Ant:
![nomino_ht_json](https://user-images.githubusercontent.com/48215082/87141172-51329400-c2c0-11ea-93af-c85bc16717c2.png)

Present CSV file we have:
![nomino_ht_csv](https://user-images.githubusercontent.com/48215082/87141182-57287500-c2c0-11ea-9f57-9d896d6f2dd6.png)

Can we have that mapper file which gave us the NOMINO MRB and HumanTrafficking JSON files? 

Thanks.

**Comment by antaenc** [comment]
Saravanan,
   Sending the 2 files pre mapped for you. As per the email I'll work on the other files next week and then instructions to enable you to perform these mappings with the tools yourself. 

Ant

**Comment by SaravananKalimuthu21** [comment]
Thank you Ant.

**Comment by SaravananKalimuthu21** [comment]
Hi Ant,

Any updates on the other mapper files?

**Comment by antaenc** [comment]
Saravanan - I'm working on them as a priority to make them available today.

**Comment by antaenc** [comment]
Saravanan, I've sent you an email with details and examples due to the nature of the data. Additionally, a new and improved CSV mapping tool is coming very shortly.
